### PR TITLE
Patient appt list added to desktop view

### PR DESCRIPTION
**Pull request by johnny2smooth**

### CODE REVIEW

**Review by kylegoodwin — COMMENTED** [review]
Lets make this full width 
Screen Shot 2022-10-07 at 7 05 02 PM

Also we should make the appointments page not cover the sidebar on desktop, its kind of confusing behavior

Screen Shot 2022-10-07 at 7 05 24 PM

**Comment by kylegoodwin** [comment]
Requested some changes  ^ see above

**Review by kylegoodwin — CHANGES_REQUESTED** [review]
Sorry I added the changes I want in seperate comments but:

- Lets make the appointment thing full width on the patient profile
- Lets refactor to make the appointment page not full page, so the sidebar is visible
    - Check the way we do stuff on the information tab here, I think it might help? Could be wrong

**Comment by johnny2smooth** [comment]
> 
I agree that we should keep the sidebar visible on desktop. There are a couple other routes that don't render the sidebar, like AddAppointment. Maybe we can check out a different branch and synchronize all of the ones that are only optimized for mobile with the desktop.

**Pull request merged**
