### PR TITLE
Feature/specify other appointment

### PR DESCRIPTION
**Pull request by kylegoodwin**
Creating this PR from Johns changes

- Conditionally renders an input to change the title of an "Other" appointment, and displays this information on the list of appointments

### CODE REVIEW

**Comment by kylegoodwin** [comment]
@johnny2smooth  tried out these changes but looks like its not showing the appointment type for appointments that are not of the "Other" type.

ie. If I add a Sputum Test, the title just shows up as blank.
Screen Shot 2022-07-26 at 11 32 45 AM

**Comment by kylegoodwin** [comment]
Also for the label on the new input we have this translation string - appointments.otherType

This will look like - "What type of appointment?" instead of "Select an appointment type", which will make more sense because its a text input.

**Comment by johnny2smooth** [comment]
I see what happened. The old appointments did not have an initial otherType value of '', so they were null by default. To render the otherType component i was making sure that the title !== ''. Therefore the null values were valid. Null was the title instead of conditionally rendering the original category name.

**Review by kylegoodwin — COMMENTED** [review]
This all looks good! I made a small change to fix the issue that I introduced in the ShortDate component. 

Thanks John

**Pull request merged**
